### ISSUE TITLE
能否支持video标签呢

### ISSUE THREAD

**Issue by GLW-Eric** [zhanziyang/wxmlify#1]
您好，我的小程序富文本中有video标签，请问有办法解析么

**Comment by zhanziyang** [comment]
目前还不行哦，我晚点做video支持，今天或者明天。谢谢您的提议。

**Comment by zhanziyang** [comment]
v1.1.0 添加对`<video>`标签的支持，但是不支持用`<source>`指定视频源，src属性必须放在`<video>`标签上。
谢谢您的提议！
